#!/usr/bin/env python3
"""Bounded Phase 2E value-path probe for one official ReboCap SDK client.

Only the newest canonical pose is retained in memory. Each consumed value runs
through a synthetic Target FK, eight anchors, and sixteen OSC encode/decode
operations; no generated bytes or motion values are persisted or transmitted.
The synthetic skeleton proves the value path only, not an avatar or product.
"""

from __future__ import annotations

import argparse
import ctypes
from dataclasses import dataclass
from enum import Enum
import json
import math
from pathlib import Path
import signal
import sys
import threading
import time
from typing import Any, Callable, Optional

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from reboretarget import (
    LatestPoseSlot,
    LatestPoseState,
    PublishResult,
    ReboCapDeltaPose,
    SourcePose,
    adapt_rebocap_delta_pose,
    build_osc_tracker_poses,
    build_tracker_messages,
    build_tracker_transforms,
    decode_osc_float3_message,
    encode_osc_float3_message,
    retarget_pose,
    synthetic_tracker_anchor_definitions,
)
from tests.synthetic_fixtures import synthetic_human_skeleton


Clock = Callable[[], float]
Waiter = Callable[[threading.Event, float], None]
ProcessGuard = Callable[[int], bool]


class AbortReason(str, Enum):
    NONE = "NONE"
    USER_STOP = "USER_STOP"
    PROCESS_NOT_ALIVE = "PROCESS_NOT_ALIVE"
    PROCESS_STATE_AMBIGUOUS = "PROCESS_STATE_AMBIGUOUS"
    SDK_IMPORT_FAILED = "SDK_IMPORT_FAILED"
    SDK_CONSTRUCTION_FAILED = "SDK_CONSTRUCTION_FAILED"
    SDK_CALLBACK_REGISTRATION_FAILED = "SDK_CALLBACK_REGISTRATION_FAILED"
    SDK_OPEN_FAILED = "SDK_OPEN_FAILED"
    SDK_ABNORMAL_CLOSE = "SDK_ABNORMAL_CLOSE"
    SDK_CLOSE_FAILED = "SDK_CLOSE_FAILED"
    INVALID_RECEIVE_TIMESTAMP = "INVALID_RECEIVE_TIMESTAMP"
    INVALID_ROOT_TRANSLATION = "INVALID_ROOT_TRANSLATION"
    INVALID_POSE_COUNT = "INVALID_POSE_COUNT"
    INVALID_QUATERNION = "INVALID_QUATERNION"
    INVALID_QUATERNION_NORM = "INVALID_QUATERNION_NORM"
    INVALID_SOURCE_TIMESTAMP = "INVALID_SOURCE_TIMESTAMP"
    RECEIVE_TIMESTAMP_ORDER = "RECEIVE_TIMESTAMP_ORDER"
    SOURCE_TIMESTAMP_ORDER = "SOURCE_TIMESTAMP_ORDER"
    ADAPTER_ERROR = "ADAPTER_ERROR"
    STALE_LATEST_POSE = "STALE_LATEST_POSE"
    PIPELINE_ERROR = "PIPELINE_ERROR"
    CLOCK_REGRESSION = "CLOCK_REGRESSION"


def _finite(value: Any, label: str) -> float:
    if isinstance(value, bool):
        raise ValueError(f"{label} must be finite and not Boolean")
    try:
        result = float(value)
    except (TypeError, ValueError) as error:
        raise ValueError(f"{label} must be finite") from error
    if not math.isfinite(result):
        raise ValueError(f"{label} must be finite")
    return result


@dataclass(frozen=True, slots=True)
class ProbeConfig:
    duration_seconds: float = 20.0
    stale_after_seconds: float = 0.250
    quaternion_norm_tolerance: float = 1e-4
    consumer_hz: float = 30.0
    pure_pipeline_p99_budget_ms: float = 10.0
    minimum_callbacks: int = 100
    minimum_callback_hz: float = 45.0
    maximum_callback_hz: float = 75.0

    def __post_init__(self) -> None:
        numeric = {
            name: _finite(getattr(self, name), name)
            for name in (
                "duration_seconds",
                "stale_after_seconds",
                "quaternion_norm_tolerance",
                "consumer_hz",
                "pure_pipeline_p99_budget_ms",
                "minimum_callback_hz",
                "maximum_callback_hz",
            )
        }
        if not 1.0 <= numeric["duration_seconds"] <= 60.0:
            raise ValueError("duration_seconds must be between 1 and 60")
        if any(
            numeric[name] <= 0.0
            for name in (
                "stale_after_seconds",
                "quaternion_norm_tolerance",
                "consumer_hz",
                "pure_pipeline_p99_budget_ms",
                "minimum_callback_hz",
            )
        ):
            raise ValueError("probe thresholds and rates must be positive")
        if numeric["maximum_callback_hz"] < numeric["minimum_callback_hz"]:
            raise ValueError("callback Hz acceptance range is invalid")
        if (
            isinstance(self.minimum_callbacks, bool)
            or not isinstance(self.minimum_callbacks, int)
            or self.minimum_callbacks <= 0
        ):
            raise ValueError("minimum_callbacks must be a positive integer")
        for name, value in numeric.items():
            object.__setattr__(self, name, value)


class _Histogram:
    """Bounded-memory percentile approximation."""

    def __init__(self, width: float, maximum: float) -> None:
        self.width = width
        self.maximum = maximum
        self.bins = [0] * (math.ceil(maximum / width) + 1)
        self.count = self.overflow = 0
        self.total = 0.0
        self.minimum = math.inf
        self.maximum_seen = -math.inf

    def add(self, value: float) -> None:
        if not math.isfinite(value) or value < 0.0:
            return
        self.count += 1
        self.total += value
        self.minimum = min(self.minimum, value)
        self.maximum_seen = max(self.maximum_seen, value)
        if value > self.maximum:
            self.overflow += 1
        else:
            self.bins[min(int(value / self.width), len(self.bins) - 1)] += 1

    def percentile(self, fraction: float) -> Optional[float]:
        target = max(1, math.ceil(self.count * fraction))
        seen = 0
        for index, amount in enumerate(self.bins):
            seen += amount
            if seen >= target:
                return round(index * self.width, 6)
        return round(self.maximum_seen, 6) if self.count else None

    def summary(self) -> dict[str, Any]:
        return {
            "count": self.count,
            "mean": round(self.total / self.count, 6) if self.count else None,
            "min": round(self.minimum, 6) if self.count else None,
            "p50": self.percentile(0.50),
            "p95": self.percentile(0.95),
            "p99": self.percentile(0.99),
            "max": round(self.maximum_seen, 6) if self.count else None,
            "overflow_count": self.overflow,
        }


class _InputError(Exception):
    def __init__(self, reason: AbortReason) -> None:
        super().__init__(reason.value)
        self.reason = reason


COUNT_NAMES = (
    "callbacks_received", "callbacks_while_accepting", "late_callbacks_rejected",
    "invalid_callbacks", "delta_pose_created", "canonical_pose_created",
    "publish_attempts", "publish_accepted", "publish_rejected",
    "receive_order_rejections", "source_order_rejections",
    "timestamp_regressions", "receive_gaps_ge_50ms", "receive_gaps_ge_100ms",
    "receive_gaps_ge_250ms", "receive_bursts_lt_4ms",
    "gap_followed_burst_candidates", "source_jumps_ge_250ms", "snapshots_taken",
    "processed_unique_sequences", "unseen_replacements_before_snapshot",
    "sequence_gap_drops", "pipeline_successes", "tracker_sets_of_eight",
    "message_sets_of_sixteen", "decoded_messages",
)


class LiveRetargetSafetyProbe:
    """Callback validation, capacity-one handoff, and aggregate evidence."""

    def __init__(self, config: ProbeConfig, *, clock: Clock = time.monotonic) -> None:
        self.config, self._clock = config, clock
        self._lock, self._callback_lock = threading.Lock(), threading.Lock()
        self.wake = threading.Event()
        self.slot: LatestPoseSlot[SourcePose] = LatestPoseSlot(config.stale_after_seconds)
        self._source = synthetic_human_skeleton()
        self._target = synthetic_human_skeleton(
            upper_leg=0.52, lower_leg=0.50, shoulder_width_scale=1.10
        )
        self._anchors = synthetic_tracker_anchor_definitions(self._target)
        self._accepting, self._intentional_close = True, False
        self._abort_reason = AbortReason.NONE
        self._normal_deadline_reached = self._natural_disconnect_seen = False
        self._run_started = self._close_started = None
        self._last_receive = self._first_accepted = self._last_accepted = None
        self._last_source = None
        self._last_receive_was_gap = False
        self._last_snapshotted_sequence = 0
        self._last_processed_sequence = 0
        self.process_alive_start = self.process_alive_end = False
        self.lifecycle = {
            "sdk_constructor_attempts": 0, "sdk_client_instances": 0,
            "sdk_open_attempts": 0, "sdk_open_successes": 0,
            "sdk_open_result_code": None, "sdk_close_attempts": 0,
            "sdk_close_successes": 0,
        }
        self.counts = {name: 0 for name in COUNT_NAMES}
        self.histograms = {
            "receive_interval": _Histogram(0.5, 1000.0),
            "source_interval": _Histogram(0.5, 1000.0),
            "validation": _Histogram(0.05, 100.0),
            "adapter": _Histogram(0.05, 100.0),
            "snapshot": _Histogram(0.05, 100.0),
            "target_fk": _Histogram(0.05, 100.0),
            "anchors": _Histogram(0.05, 100.0),
            "osc_representation": _Histogram(0.05, 100.0),
            "osc_codec": _Histogram(0.05, 100.0),
            "pure_pipeline": _Histogram(0.05, 100.0),
            "receive_to_decode": _Histogram(0.5, 2000.0),
        }
        self.controlled_stale_clear = self.final_disconnected_clear = False

    @property
    def abort_reason(self) -> AbortReason:
        with self._lock:
            return self._abort_reason

    def _inc(self, name: str, amount: int = 1) -> None:
        with self._lock:
            self.counts[name] += amount

    def _timing(self, name: str, start: float, end: float) -> None:
        with self._lock:
            self.histograms[name].add(max(0.0, (end - start) * 1000.0))

    def _abort(self, reason: AbortReason) -> None:
        with self._lock:
            if self._abort_reason is AbortReason.NONE:
                self._abort_reason = reason
            self._accepting = False
        self.slot.mark_disconnected()
        self.wake.set()

    def request_user_stop(self) -> None:
        self._abort(AbortReason.USER_STOP)

    def record_run_start(self, timestamp: float) -> None:
        self._run_started = timestamp

    def record_close_start(self, timestamp: float) -> None:
        with self._callback_lock:
            with self._lock:
                self._close_started = timestamp
                self._intentional_close = True
                self._accepting = False

    def record_sdk_open_result(self, result: Any) -> bool:
        self.lifecycle["sdk_open_attempts"] += 1
        if isinstance(result, bool) or not isinstance(result, int):
            return False
        self.lifecycle["sdk_open_result_code"] = result
        if result == 0:
            self.lifecycle["sdk_open_successes"] += 1
            return True
        return False

    def _raw_values(self, trans: Any, pose24: Any, source: Any) -> tuple:
        try:
            root = tuple(trans)
            if len(root) != 3:
                raise ValueError
            root = tuple(_finite(value, "root component") for value in root)
        except (TypeError, ValueError):
            raise _InputError(AbortReason.INVALID_ROOT_TRANSLATION)
        try:
            rotations = tuple(pose24)
        except TypeError:
            raise _InputError(AbortReason.INVALID_POSE_COUNT)
        if len(rotations) != 24:
            raise _InputError(AbortReason.INVALID_POSE_COUNT)
        checked = []
        for raw in rotations:
            try:
                values = tuple(raw)
                if len(values) != 4:
                    raise ValueError
                values = tuple(_finite(value, "quaternion") for value in values)
            except (TypeError, ValueError):
                raise _InputError(AbortReason.INVALID_QUATERNION)
            norm = math.sqrt(sum(value * value for value in values))
            if abs(norm - 1.0) > self.config.quaternion_norm_tolerance:
                raise _InputError(AbortReason.INVALID_QUATERNION_NORM)
            checked.append(values)
        try:
            source_value = _finite(source, "source_timestamp")
        except ValueError:
            raise _InputError(AbortReason.INVALID_SOURCE_TIMESTAMP)
        return root, tuple(checked), source_value

    def on_pose(self, sdk: Any, trans: Any, pose24: Any, static: Any, source_timestamp: Any) -> None:
        with self._callback_lock:
            self._on_pose(sdk, trans, pose24, static, source_timestamp)

    def _on_pose(self, _sdk: Any, trans: Any, pose24: Any, _static: Any, source_timestamp: Any) -> None:
        try:
            receive = _finite(self._clock(), "receive_monotonic")
            if receive < 0.0:
                raise ValueError
        except ValueError:
            self._inc("invalid_callbacks")
            self._abort(AbortReason.INVALID_RECEIVE_TIMESTAMP)
            return
        with self._lock:
            self.counts["callbacks_received"] += 1
            if not self._accepting:
                self.counts["late_callbacks_rejected"] += 1
                return
            self.counts["callbacks_while_accepting"] += 1
            if self._last_receive is not None:
                interval_ms = (receive - self._last_receive) * 1000.0
                self.histograms["receive_interval"].add(interval_ms)
                if interval_ms >= 50.0:
                    self.counts["receive_gaps_ge_50ms"] += 1
                if interval_ms >= 100.0:
                    self.counts["receive_gaps_ge_100ms"] += 1
                if interval_ms >= 250.0:
                    self.counts["receive_gaps_ge_250ms"] += 1
                if interval_ms < 4.0:
                    self.counts["receive_bursts_lt_4ms"] += 1
                    if self._last_receive_was_gap:
                        self.counts["gap_followed_burst_candidates"] += 1
                self._last_receive_was_gap = interval_ms >= 50.0
            self._last_receive = receive
        try:
            root, rotations, source = self._raw_values(trans, pose24, source_timestamp)
        except _InputError as error:
            self._inc("invalid_callbacks")
            self._abort(error.reason)
            return
        validated_at = self._clock()
        self._timing("validation", receive, validated_at)
        with self._lock:
            if self._last_source is not None:
                source_interval_ms = (source - self._last_source) * 1000.0
                self.histograms["source_interval"].add(source_interval_ms)
                if source_interval_ms >= 250.0:
                    self.counts["source_jumps_ge_250ms"] += 1
            self._last_source = source
        adapter_started = self._clock()
        try:
            delta = ReboCapDeltaPose.from_rebocap24(root, rotations)
            self._inc("delta_pose_created")
            canonical = adapt_rebocap_delta_pose(delta, self._source)
            self._inc("canonical_pose_created")
        except Exception:
            self._inc("invalid_callbacks")
            self._abort(AbortReason.ADAPTER_ERROR)
            return
        self._timing("adapter", adapter_started, self._clock())
        self._inc("publish_attempts")
        try:
            result = self.slot.publish(
                canonical, receive_monotonic=receive, source_timestamp=source
            )
        except ValueError:
            self._abort(AbortReason.INVALID_RECEIVE_TIMESTAMP)
            return
        if result is PublishResult.ACCEPTED:
            with self._lock:
                self.counts["publish_accepted"] += 1
                accepted_sequence = self.counts["publish_accepted"]
                if accepted_sequence - 1 > self._last_snapshotted_sequence:
                    self.counts["unseen_replacements_before_snapshot"] += 1
                if self._first_accepted is None:
                    self._first_accepted = receive
                self._last_accepted = receive
            return
        self._inc("publish_rejected")
        self._inc("timestamp_regressions")
        if result is PublishResult.REJECTED_RECEIVE_ORDER:
            self._inc("receive_order_rejections")
            self._abort(AbortReason.RECEIVE_TIMESTAMP_ORDER)
        elif result is PublishResult.REJECTED_SOURCE_ORDER:
            self._inc("source_order_rejections")
            self._abort(AbortReason.SOURCE_TIMESTAMP_ORDER)
        else:
            self._abort(AbortReason.PIPELINE_ERROR)

    def on_sdk_close(self, _sdk: Any) -> None:
        with self._lock:
            intentional = self._intentional_close
            self._natural_disconnect_seen |= not intentional
        self.slot.mark_disconnected()
        if intentional:
            self.wake.set()
        else:
            self._abort(AbortReason.SDK_ABNORMAL_CLOSE)

    def process_latest(self) -> None:
        started = self._clock()
        try:
            snapshot = self.slot.snapshot_at(started)
        except ValueError:
            self._abort(AbortReason.INVALID_RECEIVE_TIMESTAMP)
            return
        self._inc("snapshots_taken")
        self._timing("snapshot", started, self._clock())
        if snapshot.state is LatestPoseState.STALE:
            self._abort(AbortReason.STALE_LATEST_POSE)
            return
        if snapshot.state is not LatestPoseState.VALID or snapshot.sample is None:
            return
        sample = snapshot.sample
        with self._lock:
            if sample.sequence == self._last_processed_sequence:
                return
            self._last_snapshotted_sequence = sample.sequence
            gap = sample.sequence - self._last_processed_sequence - 1
        if gap < 0:
            self._abort(AbortReason.PIPELINE_ERROR)
            return
        pure_started = self._clock()
        try:
            stage = pure_started
            target = retarget_pose(sample.value, self._source, self._target)
            now = self._clock()
            self._timing("target_fk", stage, now)
            stage = now
            transforms = build_tracker_transforms(target, self._anchors)
            now = self._clock()
            self._timing("anchors", stage, now)
            if len(transforms) != 8:
                raise ValueError
            stage = now
            poses = build_osc_tracker_poses(transforms)
            messages = build_tracker_messages(poses)
            now = self._clock()
            self._timing("osc_representation", stage, now)
            if len(poses) != 8 or len(messages) != 16:
                raise ValueError
            expected_addresses = {
                f"/tracking/trackers/{slot}/{kind}"
                for slot in range(1, 9)
                for kind in ("position", "rotation")
            }
            if {message.address for message in messages} != expected_addresses:
                raise ValueError
            stage = now
            decoded_count = 0
            for message in messages:
                packet = encode_osc_float3_message(message)
                decoded = decode_osc_float3_message(packet)
                if decoded.address != message.address or any(
                    not math.isclose(a, b, rel_tol=1e-6, abs_tol=1e-5)
                    for a, b in zip(decoded.values, message.values)
                ):
                    raise ValueError
                decoded_count += 1
            finished = self._clock()
            self._timing("osc_codec", stage, finished)
        except Exception:
            self._abort(AbortReason.PIPELINE_ERROR)
            return
        if finished < sample.receive_monotonic:
            self._abort(AbortReason.CLOCK_REGRESSION)
            return
        self._timing("pure_pipeline", pure_started, finished)
        self._timing("receive_to_decode", sample.receive_monotonic, finished)
        with self._lock:
            self._last_processed_sequence = sample.sequence
            self.counts["sequence_gap_drops"] += gap
            for name in (
                "processed_unique_sequences", "pipeline_successes",
                "tracker_sets_of_eight", "message_sets_of_sixteen",
            ):
                self.counts[name] += 1
            self.counts["decoded_messages"] += decoded_count

    def finish_normal_observation(self) -> None:
        with self._callback_lock:
            with self._lock:
                if self._abort_reason is not AbortReason.NONE:
                    return
                self._accepting = False
                self._normal_deadline_reached = True
            self.slot.mark_stale()
            snapshot = self.slot.snapshot_at(self._clock())
            self.controlled_stale_clear = (
                snapshot.state is LatestPoseState.STALE and snapshot.sample is None
            )
            self.finish_disconnected_clear()

    def finish_disconnected_clear(self) -> None:
        self.slot.mark_disconnected()
        snapshot = self.slot.snapshot_at(self._clock())
        self.final_disconnected_clear = (
            snapshot.state is LatestPoseState.DISCONNECTED and snapshot.sample is None
        )

    def aggregate_result(self) -> dict[str, Any]:
        final = self.slot.snapshot_at(self._clock())
        with self._lock:
            counts, life = dict(self.counts), dict(self.lifecycle)
            span = (
                self._last_accepted - self._first_accepted
                if self._first_accepted is not None and self._last_accepted is not None
                else None
            )
            rate = (
                (counts["publish_accepted"] - 1) / span
                if span and counts["publish_accepted"] > 1 else None
            )
            duration = (
                self._close_started - self._run_started
                if self._run_started is not None and self._close_started is not None
                else None
            )
            natural_disconnect = self._natural_disconnect_seen
            abort, normal = self._abort_reason, self._normal_deadline_reached
            timing = {name: value.summary() for name, value in self.histograms.items()}
        failed, insufficient = [], []
        if not normal:
            insufficient.append("NORMAL_DEADLINE_NOT_REACHED")
        if not self.process_alive_start or not self.process_alive_end:
            failed.append("REBOCAP_PROCESS_GUARD")
        if life["sdk_client_instances"] != 1:
            failed.append("ONE_CLIENT_INSTANCE")
        if life["sdk_open_attempts"] != 1 or life["sdk_open_successes"] != 1:
            failed.append("ONE_SUCCESSFUL_OPEN")
        if life["sdk_close_attempts"] != 1 or life["sdk_close_successes"] != 1:
            failed.append("ONE_SUCCESSFUL_CLOSE")
        if counts["publish_accepted"] < self.config.minimum_callbacks:
            insufficient.append("MINIMUM_CALLBACK_COUNT")
        if rate is None:
            insufficient.append("CALLBACK_RATE")
        elif not self.config.minimum_callback_hz <= rate <= self.config.maximum_callback_hz:
            failed.append("CALLBACK_RATE_RANGE")
        callback_path = (
            counts["callbacks_while_accepting"] == counts["delta_pose_created"]
            == counts["canonical_pose_created"] == counts["publish_attempts"]
            == counts["publish_accepted"]
        )
        if counts["invalid_callbacks"] or not callback_path:
            failed.append("CALLBACK_VALUE_PATH_COUNTS")
        if counts["publish_rejected"] or counts["timestamp_regressions"]:
            failed.append("TIMESTAMP_ORDER")
        processed = counts["processed_unique_sequences"]
        if processed <= 0:
            insufficient.append("PROCESSED_SEQUENCE_COUNT")
        if not (
            processed == counts["pipeline_successes"] == counts["tracker_sets_of_eight"]
            == counts["message_sets_of_sixteen"]
            and counts["decoded_messages"] == processed * 16
        ):
            failed.append("PIPELINE_COUNTS")
        p99 = timing["pure_pipeline"]["p99"]
        if p99 is None:
            insufficient.append("PURE_PIPELINE_P99")
        elif p99 > self.config.pure_pipeline_p99_budget_ms:
            failed.append("PURE_PIPELINE_P99_BUDGET")
        if not self.controlled_stale_clear:
            failed.append("CONTROLLED_STALE_CLEAR")
        if not self.final_disconnected_clear:
            failed.append("FINAL_DISCONNECTED_CLEAR")
        if duration is None:
            insufficient.append("OBSERVATION_DURATION")
        elif duration > 60.0:
            failed.append("SIXTY_SECOND_MAXIMUM")
        status = (
            "ABORTED" if abort is not AbortReason.NONE else
            "FAIL" if failed else "UNVERIFIED" if insufficient else "PASS"
        )
        counts["slot_replacements_total"] = max(0, counts["publish_accepted"] - 1)
        counts["latest_sequence"] = counts["publish_accepted"]
        life.update({
            "process_alive_start": self.process_alive_start,
            "process_alive_end": self.process_alive_end,
            "observation_duration_seconds": round(duration, 6) if duration is not None else None,
            "natural_disconnect": "TRIGGERED" if natural_disconnect else "NOT_TRIGGERED",
            "external_disconnect_evidence": (
                "CONFIRMED" if natural_disconnect else "UNVERIFIED / NOT OBSERVED"
            ),
        })
        return {
            "schema": "reboretarget.phase2e.aggregate.v1", "status": status,
            "abort_reason": abort.value, "acceptance_failed": sorted(set(failed)),
            "acceptance_insufficient": sorted(set(insufficient)),
            "fixture": "synthetic_value_path_not_avatar",
            "configuration": {
                "duration_seconds": self.config.duration_seconds,
                "stale_after_seconds": self.config.stale_after_seconds,
                "quaternion_norm_tolerance": self.config.quaternion_norm_tolerance,
                "consumer_hz": self.config.consumer_hz,
                "pure_pipeline_p99_budget_ms": self.config.pure_pipeline_p99_budget_ms,
                "minimum_callbacks": self.config.minimum_callbacks,
                "callback_hz_range": [self.config.minimum_callback_hz, self.config.maximum_callback_hz],
            },
            "lifecycle": life, "counts": counts,
            "callback_rate": {
                "accepted_span_seconds": round(span, 6) if span is not None else None,
                "average_hz": round(rate, 6) if rate else None,
            },
            "validation": {
                "expected_joint_count": 24,
                "invalid_root_translation": int(
                    abort is AbortReason.INVALID_ROOT_TRANSLATION
                ),
                "invalid_pose_count": int(abort is AbortReason.INVALID_POSE_COUNT),
                "invalid_quaternion": int(
                    abort in (
                        AbortReason.INVALID_QUATERNION,
                        AbortReason.INVALID_QUATERNION_NORM,
                    )
                ),
                "invalid_source_timestamp": int(
                    abort is AbortReason.INVALID_SOURCE_TIMESTAMP
                ),
                "adapter_errors": int(abort is AbortReason.ADAPTER_ERROR),
            },
            "cadence_thresholds_ms": {
                "receive_gap": [50.0, 100.0, 250.0],
                "receive_burst_less_than": 4.0,
                "source_jump": 250.0,
            },
            "timings_ms": timing,
            "invalidation": {
                "controlled_stale_clear": self.controlled_stale_clear,
                "final_disconnected_clear": self.final_disconnected_clear,
                "latest_sample_present": final.sample is not None,
                "abnormal_close_callback_wired": True,
                "abnormal_close_forced": False,
            },
            "safety": {
                "raw_pose_frames_persisted": 0, "raw_time_series_persisted": 0,
                "message_bytes_persisted": 0, "direct_transport_sends": 0,
                "osc_transmissions": 0, "reconnect_attempts": 0,
                "multi_client_attempts": 0, "application_process_setting_changes": 0,
            },
        }


def process_alive(process_id: int) -> bool:
    """Read one supplied Windows process handle without changing it."""
    if sys.platform != "win32":
        return True
    handle = ctypes.windll.kernel32.OpenProcess(0x00100000, False, process_id)
    if not handle:
        return False
    try:
        return ctypes.windll.kernel32.WaitForSingleObject(handle, 0) == 0x00000102
    finally:
        ctypes.windll.kernel32.CloseHandle(handle)


def _default_wait(event: threading.Event, timeout: float) -> None:
    event.wait(max(0.0, timeout))


def execute_probe(
    sdk_module: Any, *, port: int, process_id: int, config: ProbeConfig,
    clock: Clock = time.monotonic, waiter: Waiter = _default_wait,
    process_guard: ProcessGuard = process_alive,
    stop_event: Optional[threading.Event] = None,
) -> dict[str, Any]:
    """Open one SDK client once, run the bounded probe, and close it once."""
    probe = LiveRetargetSafetyProbe(config, clock=clock)
    stop, sdk, run_started = stop_event or threading.Event(), None, None
    try:
        try:
            probe.process_alive_start = probe.process_alive_end = bool(process_guard(process_id))
        except Exception:
            probe._abort(AbortReason.PROCESS_STATE_AMBIGUOUS)
        if probe.abort_reason is AbortReason.NONE and not probe.process_alive_start:
            probe._abort(AbortReason.PROCESS_NOT_ALIVE)
        if probe.abort_reason is AbortReason.NONE:
            probe.lifecycle["sdk_constructor_attempts"] += 1
            try:
                sdk = sdk_module.RebocapWsSdk(
                    coordinate_type=sdk_module.CoordinateType.UnityCoordinate,
                    use_global_rotation=True,
                )
                probe.lifecycle["sdk_client_instances"] += 1
            except Exception:
                probe._abort(AbortReason.SDK_CONSTRUCTION_FAILED)
        if probe.abort_reason is AbortReason.NONE:
            try:
                sdk.set_pose_msg_callback(probe.on_pose)
                sdk.set_exception_close_callback(probe.on_sdk_close)
            except Exception:
                probe._abort(AbortReason.SDK_CALLBACK_REGISTRATION_FAILED)
        if probe.abort_reason is AbortReason.NONE:
            try:
                run_started = _finite(clock(), "run_started")
                probe.record_run_start(run_started)
                result = sdk.open(port)
            except Exception:
                probe.lifecycle["sdk_open_attempts"] += 1
                probe._abort(AbortReason.SDK_OPEN_FAILED)
            else:
                if not probe.record_sdk_open_result(result):
                    probe._abort(AbortReason.SDK_OPEN_FAILED)
        if probe.abort_reason is AbortReason.NONE:
            deadline, period = run_started + config.duration_seconds, 1.0 / config.consumer_hz
            while probe.abort_reason is AbortReason.NONE:
                if stop.is_set():
                    probe.request_user_stop()
                    break
                try:
                    probe.process_alive_end = bool(process_guard(process_id))
                except Exception:
                    probe._abort(AbortReason.PROCESS_STATE_AMBIGUOUS)
                    break
                if not probe.process_alive_end:
                    probe._abort(AbortReason.PROCESS_NOT_ALIVE)
                    break
                try:
                    now = _finite(clock(), "loop_monotonic")
                except ValueError:
                    probe._abort(AbortReason.INVALID_RECEIVE_TIMESTAMP)
                    break
                if now >= deadline:
                    break
                probe.wake.clear()
                probe.process_latest()
                remaining = deadline - _finite(clock(), "loop_monotonic")
                if probe.abort_reason is not AbortReason.NONE or remaining <= 1e-9:
                    break
                waiter(probe.wake, min(period, remaining))
            if probe.abort_reason is AbortReason.NONE:
                try:
                    probe.process_alive_end = bool(process_guard(process_id))
                except Exception:
                    probe._abort(AbortReason.PROCESS_STATE_AMBIGUOUS)
                if not probe.process_alive_end:
                    probe._abort(AbortReason.PROCESS_NOT_ALIVE)
                else:
                    probe.process_latest()
                    if probe.abort_reason is AbortReason.NONE:
                        probe.finish_normal_observation()
    finally:
        if sdk is not None:
            probe.record_close_start(clock())
            probe.lifecycle["sdk_close_attempts"] += 1
            try:
                sdk.close()
                probe.lifecycle["sdk_close_successes"] += 1
            except Exception:
                probe._abort(AbortReason.SDK_CLOSE_FAILED)
        probe.finish_disconnected_clear()
    return probe.aggregate_result()


def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdk-root", type=Path, required=True)
    parser.add_argument("--port", type=int, required=True)
    parser.add_argument("--process-id", type=int, required=True)
    parser.add_argument("--duration-seconds", type=float, default=20.0)
    parser.add_argument("--stale-after-seconds", type=float, default=0.250)
    parser.add_argument("--quaternion-norm-tolerance", type=float, default=1e-4)
    parser.add_argument("--consumer-hz", type=float, default=30.0)
    parser.add_argument("--pure-pipeline-p99-budget-ms", type=float, default=10.0)
    args = parser.parse_args(argv)
    if not 1 <= args.port <= 65535 or args.process_id <= 0:
        parser.error("port and process-id must be positive and in range")
    try:
        args.config = ProbeConfig(
            duration_seconds=args.duration_seconds,
            stale_after_seconds=args.stale_after_seconds,
            quaternion_norm_tolerance=args.quaternion_norm_tolerance,
            consumer_hz=args.consumer_hz,
            pure_pipeline_p99_budget_ms=args.pure_pipeline_p99_budget_ms,
        )
    except ValueError as error:
        parser.error(str(error))
    return args


def _import_failure(config: ProbeConfig) -> dict[str, Any]:
    probe = LiveRetargetSafetyProbe(config)
    probe._abort(AbortReason.SDK_IMPORT_FAILED)
    return probe.aggregate_result()


def main(argv: Optional[list[str]] = None) -> int:
    args, stop = _parse_args(argv), threading.Event()
    signal.signal(signal.SIGINT, lambda _signum, _frame: stop.set())
    signal.signal(signal.SIGTERM, lambda _signum, _frame: stop.set())
    sys.path.insert(0, str(args.sdk_root.resolve()))
    try:
        from rebocap_ws_sdk import rebocap_ws_sdk
    except Exception:
        report = _import_failure(args.config)
    else:
        report = execute_probe(
            rebocap_ws_sdk, port=args.port, process_id=args.process_id,
            config=args.config, stop_event=stop,
        )
    print("RESULT_JSON=" + json.dumps(report, sort_keys=True, separators=(",", ":")))
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
