"""Pure, offline mathematics for ReboRetarget experiments."""

from .fk import (
    REBOCAP_24_JOINT_NAMES,
    JointDefinition,
    JointDiagnostic,
    Quaternion,
    SkeletonDefinition,
    SourcePose,
    TargetPose,
    Transform,
    forward_kinematics,
    global_to_local_rotations,
    leg_lengths_from_controls,
    quaternion_from_axis_angle,
    quaternion_inverse,
    quaternion_multiply,
    quaternion_rotation_angle_degrees,
    quaternions_equivalent,
    retarget_pose,
    rotate_vector,
    validate_rebocap24_skeleton,
)

__all__ = [
    "REBOCAP_24_JOINT_NAMES",
    "JointDefinition",
    "JointDiagnostic",
    "Quaternion",
    "SkeletonDefinition",
    "SourcePose",
    "TargetPose",
    "Transform",
    "forward_kinematics",
    "global_to_local_rotations",
    "leg_lengths_from_controls",
    "quaternion_from_axis_angle",
    "quaternion_inverse",
    "quaternion_multiply",
    "quaternion_rotation_angle_degrees",
    "quaternions_equivalent",
    "retarget_pose",
    "rotate_vector",
    "validate_rebocap24_skeleton",
]
